version: "3"

services:
  e2e-tests:
    build: ./e2e-tests
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
      - firefox
      - chrome

  selenium-hub:
    image: selenium/hub:3.141.59-zirconium
    environment:
      GRID_DEBUG: "true"
      GRID_TIMEOUT: 90

  firefox:
    image: selenium/node-firefox:3.141.59-zirconium
    volumes:
      - /dev/shm:/dev/shm
    environment:
      HUB_HOST: "selenium-hub"
      HUB_PORT: 4444
      NODE_MAX_INSTANCES: 10
      NODE_MAX_SESSION: 10
      GRID_DEBUG: "true"
    depends_on:
      - selenium-hub

  chrome:
    image: selenium/node-firefox:3.141.59-zirconium
    volumes:
      - /dev/shm:/dev/shm
    environment:
      HUB_HOST: "selenium-hub"
      HUB_PORT: 4444
      NODE_MAX_INSTANCES: 10
      NODE_MAX_SESSION: 10
    depends_on:
      - selenium-hub
